OnlineMedical/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();




Route::namespace('Admin')->prefix('home-admin')->middleware('auth')->group(function() {
    
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/questionnaires',                                   'QuestionnaireController@index')->name('show_all_questionnaires');
    Route::get('/questionnaires/create',                            'QuestionnaireController@create')->name('create_questionnaire');
    Route::get('/questionnaires/{questionnaire}/show',              'QuestionnaireController@show')->name('show_questionnaire');
    Route::get('/questionnaires/{questionnaire}/preview',           'QuestionnaireController@preview')->name('preview_questionnaire');
    Route::get('/questionnaires/{questionnaire}/set_in_production', 'QuestionnaireController@set_in_production')->name('set_questionnaire_in_production');

    Route::get('/questionnaires/{questionnaire}/edit',              'QuestionnaireController@edit')->name('edit_questionnaire');
    Route::get('/questionnaires/{questionnaire}/delete',            'QuestionnaireController@destroy')->name('delete_questionnaire');
    Route::post('/questionnaires/{questionnaire}/update',           'QuestionnaireController@update')->name('update_questionnaire');
    Route::post('/questionnaires/store',                            'QuestionnaireController@store')->name('store_questionnaire');
    Route::post('/questionnaires/{questionnaire}/question/schema',  'QuestionnaireController@make_questionnaire_schema')->name('make_questionnaire_schema');
    
    
    Route::get('/questionnaires/{questionnaire}/question/create',   'QuestionController@create')->name('create_question');
    Route::get('/questionnaires/questionnaire/{question}/edit',     'QuestionController@edit')->name('edit_question');
    Route::get('/questionnaires/questionnaire/{question}/delete',   'QuestionController@destroy')->name('delete_question');
    Route::post('/questionnaires/questionnaire/{question}/update',  'QuestionController@update')->name('update_question');
    Route::post('/questionnaires/{questionnaire}/question/store',   'QuestionController@store')->name('store_question');
    

    Route::get('/categories',                       'QuestionnaireCategoryController@index')->name('show_all_questionnaire_categories');
    Route::get('/categories/create',                'QuestionnaireCategoryController@create')->name('create_questionnaire_category');
    Route::get('/categories/{category}/delete',     'QuestionnaireCategoryController@destroy')->name('delete_questionnaire_category');
    Route::get('/categories/{category}/edit',       'QuestionnaireCategoryController@edit')->name('edit_questionnaire_category');
    Route::post('/categories/{category}/update',    'QuestionnaireCategoryController@update')->name('update_questionnaire_category');
    Route::post('/categories/store',                'QuestionnaireCategoryController@store')->name('store_questionnaire_category');


    Route::get('questionnaires/{response}/response/edit',           'ResponseController@edit')->name('edit_response');
    Route::get('questionnaires/{questionnaire}/response/create',    'ResponseController@create')->name('create_response');
    Route::get('/questionnaires/response/delete/{response}',        'ResponseController@destroy')->name('delete_response');
    Route::post('questionnaires/{response}/response/update',        'ResponseController@update')->name('update_response');
    Route::post('/questionnaires/{questionnaire}/response/store',   'ResponseController@store')->name('store_response');


    Route::get('/products',                                'ProductController@index')->name('show_all_products');
    Route::get('/products/create',                         'ProductController@create')->name('create_product');
    Route::get('/products/{product}/edit',                 'ProductController@edit')->name('edit_product');
    Route::get('/products/{product}/delete',               'ProductController@destroy')->name('delete_product');
    Route::post('/products/{product}/update',              'ProductController@update')->name('update_product');
    Route::get('/products/promotion-status{product}',      'ProductController@set_product_promotion_status')->name('set_promotion_status');
    Route::post('/products/store',                         'ProductController@store')->name('store_product');

    
    Route::get('/products/category',                    'ProductCategoryController@index')->name('show_all_product_categories');
    Route::get('/products/category/create',             'ProductCategoryController@create')->name('create_product_category');
    Route::get('/products/category/{category}/edit',    'ProductCategoryController@edit')->name('edit_product_category');
    Route::get('/products/category/{category}/delete',  'ProductCategoryController@destroy')->name('delete_product_category');
    Route::post('/products/category/{category}/update', 'ProductCategoryController@update')->name('update_product_category');
    Route::post('/products/category/store',             'ProductCategoryController@store')->name('store_product_category');
    Route::get('/products/get-main-category/{for}',     'ProductCategoryController@get_main_category')->name('get_product_main_category');


    Route::get('/products/subcategory/create',                  'PSubCategoryController@create')->name('create_product_sub_category');
    Route::get('/products/subcategory/delete/{sub_category}',   'PSubCategoryController@destroy')->name('delete_product_sub_category');
    Route::get('/products/subcategory/edit/{sub_category}',     'PSubCategoryController@edit')->name('edit_product_sub_category');
    Route::post('/products/subcategory/update/{sub_category}',  'PSubCategoryController@update')->name('update_product_sub_category');
    Route::post('/products/{category}/subcategory/store',       'PSubCategoryController@store')->name('store_product_sub_category');

    Route::get('/clinics',                      'ClinicController@index')->name('show_all_clinics');
    Route::get('/clinics/create',               'ClinicController@create')->name('create_clinic');
    Route::get('/clinics/{clinic}/edit',        'ClinicController@edit')->name('edit_clinic');
    Route::get('/clinics/{clinic}/delete',      'ClinicController@destroy')->name('delete_clinic');
    Route::post('/clinics/{clinic}/update',     'ClinicController@update')->name('update_clinic');
    Route::post('/clinics/store',               'ClinicController@store')->name('store_clinic');

    Route::get('/clinics/category',                       'ClinicCategoryController@index')->name('show_all_clinic_categories');
    Route::get('/clinics/category/create',                'ClinicCategoryController@create')->name('create_clinic_category');
    Route::get('/clinics/category/{category}/edit',       'ClinicCategoryController@edit')->name('edit_clinic_category');
    Route::get('/clinics/category/{category}/delete',     'ClinicCategoryController@destroy')->name('delete_clinic_category');
    Route::post('/clinics/category/{category}/update',    'ClinicCategoryController@update')->name('update_clinic_category');
    Route::post('/clinics/category/store',                'ClinicCategoryController@store')->name('store_clinic_category');


    Route::get('/blogs/categories', 'BlogCategoryController@index')->name('show_all_blog_categories');
    Route::get('/blogs/categories/create', 'BlogCategoryController@create')->name('create_blog_category');
    Route::post('/blogs/categories/store', 'BlogCategoryController@store')->name('store_blog_category');
    Route::get('/blogs/categories/delete/{category}', 'BlogCategoryController@destroy')->name('delete_blog_category');
    Route::get('/blogs/get-main-category/{for}',     'BlogCategoryController@get_main_category')->name('get_blog_main_category');

    Route::get('/blogs/subcategory/create',                  'BSubCategoryController@create')->name('create_blog_sub_category');
    Route::get('/blogs/subcategory/delete/{sub_category}',   'BSubCategoryController@destroy')->name('delete_blog_sub_category');
    Route::get('/blogs/subcategory/edit/{sub_category}',     'BSubCategoryController@edit')->name('edit_blog_sub_category');
    Route::post('/blogs/subcategory/update/{sub_category}',  'BSubCategoryController@update')->name('update_blog_sub_category');
    Route::post('/blogs/{category}/subcategory/store',       'BSubCategoryController@store')->name('store_blog_sub_category');

    Route::get('/blogs/', 'BlogController@index')->name('show_all_blogs');
    Route::get('/blogs/create', 'BlogController@create')->name('create_blog');
    Route::get('/blogs/show/blog-{blog}', 'BlogController@show')->name('show_blog');
    Route::get('/blogs/edit/blog-{blog}', 'BlogController@edit')->name('edit_blog');
    Route::get('/blogs/delete/blog-{blog}', 'BlogController@destroy')->name('delete_blog');
    Route::post('/blogs/update/{blog}', 'BlogController@update')->name('update_blog');
    Route::post('/blogs/store', 'BlogController@store')->name('store_blog');

});

Route::namespace('User')->name('user.')->group(function() {
    Route::get('/',                                        'WelcomeController@index')->name('welcome');
    Route::get('/questionnaires',                          'QuestionnaireController@index')->name('show_all_questionnaires');
    Route::get('/questionnaires/{questionnaire}/show',     'QuestionnaireController@show')->name('show_questionnaire');
    

OnlineMedical/resources/views/user/inc/welcome_page/blogs.blade.php
<div id="blogs" class="row">
    <div class="col-md-6 offset-md-3 text-center">
        <h1 class="custom-tablet-screen-heading-font"><strong>Најнови блогови</strong></h1>
        <div class="custom-hr"></div>
        <p class="custom-tablet-screen-p-font">Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, quam?</p>
    </div>
    <div class="col-md-10 offset-md-1">
        <div class="row">
            @forelse ($blogs as $blog)
            <div class="col-lg-4 col-md-6 my-3 hvr-shrink">
                <a href="{{route('user.show_blog', $blog->id)}}" class="text-decoration-none text-dark">
                    <div class="card border-0 shadow">
                        <div class="card-body min-vh-25 p-0 cover-bg" 
                        {{-- style="background-image: url({{asset('storage/'.$blog->cover_image)}});" --}}
                        style="background-image: url({{asset($blog->cover_image)}});"
                             >
                        </div>
                        <div class="card-footer bg-white py-4">
                            <p class="h5 text-center"><strong>{{$blog->title}}</strong></p>
                        </div>
                    </div>
                </a>
            </div>
            @empty
                
            @endforelse


        </div>
    </div>
</div>

OnlineMedical/resources/views/user/inc/welcome_page/header.blade.php
<header id="header" class="row min-vh-100 align-items-center cover-bg shadow" style="background-image: url('{{asset('user/imgs/welcome/doctor_laptop.jpg')}}');">
        <div id="header_headline_container" class="col-md-5 offset-md-1 text-light animated fadeInLeft">
          <h1 class="text-uppercase text-white custom-tablet-screen-heading-font">персонален <strong class="text-primary">медицински</strong> асистент</h1>  
          <p class="custom-tablet-screen-p-font">Место на кое можете најлесно да дојдете до едноставен и прецизен медицински совет!</p>
          <a class="btn btn-lg btn-outline-primary btn-round hvr-wobble-vertical" href="#how_it_works"><i class="fas fa-arrow-down"></i></a>
        </div>
        <div id="header_questionnaire_container" class="col-md-6 d-flex flex-column justify-content-around align-items-center animated fadeInRight">
          <h4 class="text-white">Пополнете прашалник </h4>
          <a class="hvr-buzz" href="{{route('user.show_all_questionnaires')}}"><i class="display-1 fas fa-clipboard-list"></i></a>
        </div>
        <div class="overlay"></div>
</header>

OnlineMedical/resources/views/user/inc/welcome_page/how_it_works.blade.php
<div id="how_it_works" class="row justify-content-center align-items-center min-vh-100">
    <div class="col-md-10 py-5">
        <h1 class="text-center custom-tablet-screen-heading-font"> <strong> Нашата цел </strong></h1>
        <div class="custom-hr"></div>
        <div class="row align-items-center">
            <div class="col-md-4">
                <img src="{{asset('user/imgs/welcome/we_are_in_this_together.jpg')}}" class="img-fluid rounded-circle shadow-lg border-right border-primary" alt="">
            </div>
            <div class="col-md-7 offset-md-1 my-4">
                <h1 class="text-right custom-tablet-screen-heading-font">Брзо, едноставно и лесно</h1>
                <p class="text-right custom-tablet-screen-p-font">Без разлика дали сте дома или надвор од државата, наша примарна цел е да понудиме брз пристап до одговор за Вашиот проблем, во секое време. Со пополнување на краток прашалник добивате дијагноза, предлог за терапија и листа од клиники кои имаат дежурна служба 24/7.</p>
                <div class="pull-right">
                    <a class="btn btn-outline-primary btn-round " href="{{route('user.show_all_questionnaires')}}"><small>Пополнете прашалник</small> <i class="fas fa-clipboard-list"></i></a>
                </div>
            </div>
            <div class="col-md-7 my-4">
                <h1 class="text-left custom-tablet-screen-heading-font">Подигање на свеста</h1>
                <p class="text-left custom-tablet-screen-p-font">Наша втора и не-помалку важна цел е да се подигне свеста, па така исто како прашалниците, оваа страна содржи база на блогови кои се пишувани од стручни лица, а имаат за цел да Ви понудат знаење за подобрување на општото физичко и ментално здравје.</p>
                <div class="pull-left">
                    <a class="btn btn-outline-primary btn-round" href="{{route('user.show_all_blogs')}}"><i class="fas fa-book-reader"></i>
                    <small>Кон сите блогови</small>
                </a>
                </div>
            </div>
            <div class="col-md-4 offset-md-1">
                <img src="{{asset('user/imgs/welcome/sad_smily.jpeg')}}" class="img-fluid rounded-circle shadow-lg border-left border-primary" alt="">
            </div>
        </div>
    </div>
</div>

OnlineMedical/resources/views/user/inc/welcome_page/mental_health.blade.php
<div id="mental_health" class="row justify-content-center align-items-center min-vh-100">
    <div class="col-md-10">
        <h1 class="text-center custom-tablet-screen-heading-font"> <strong> Ментално здравје </strong></h1>
        <div class="custom-hr"></div>
        <div class="row align-items-center">
            <div class="col-md-4">
                {{-- <img src="{{asset('storage/'.$blog->cover_image)}}" class="card-img" alt="..."> --}}
                <img src="{{$latest_psychology_blog->cover_image}}" class="card-img" alt="...">
            </div>
            <div class="col-md-7 offset-md-1 my-4">
                <h1 class="text-center custom-tablet-screen-heading-font">{{$latest_psychology_blog->title}}</h1>
                <p class="custom-tablet-screen-p-font">{{Str::limit(strip_tags($latest_psychology_blog->body), 300)}}</p>
                
                <a class="btn btn-outline-primary btn-round" href="{{route('user.show_blog', $latest_psychology_blog->id)}}">Прочитај повеќе</a>
            </div>
        </div>
    </div>
</div>

OnlineMedical/resources/views/user/inc/welcome_page/online_fitnes_advisor.blade.php
<div id="online_fitnes_advisor" class="row justify-content-center align-items-center">
    <div class="col-md-10">
        <h1 class="text-center custom-tablet-screen-heading-font"> <strong> Физичко здравје и фитнес </strong></h1>
        <div class="custom-hr"></div>
        <div class="row align-items-center">
            <div class="col-md-7 my-4">
                <h1 class="text-center custom-tablet-screen-heading-font">{{$latest_fitness_blog->title}}</h1>
                <p class="custom-tablet-screen-p-font">{{Str::limit(strip_tags($latest_fitness_blog->body), 300)}}</p>
                
                <a class="btn btn-outline-primary btn-round" href="{{route('user.show_blog', $latest_fitness_blog->id)}}">Прочитај повеќе</a>
            </div>
            <div class="col-md-4 offset-md-1">
                {{-- <img src="{{asset('storage/'.$blog->cover_image)}}" class="card-img" alt="..."> --}}
                <img src="{{$latest_fitness_blog->cover_image}}" class="card-img" alt="...">
            </div>
        </div>
    </div>
</div>

OnlineMedical/resources/views/user/inc/welcome_page/online_pharmacy.blade.php
<div id="online_pharmacy" class="row">
    <div class="col-md-12 text-center">
        <h1 class="my-2 display-4 custom-tablet-screen-heading-font"><strong> Палета на производи </strong></h1>
        <div class="custom-hr"></div>
    </div>
    <div class="col-md-10 offset-md-1">
        <div class="row ">
                
            @forelse ($products as $product)
                <div class="col-md-3 my-3">
                    <a href="" class="text-decoration-none" data-toggle="modal" data-target="#myDescriptionModal{{ $product->id }}">
                        <div class="card p-0 shadow">
                            <div class="card-body p-0 cursor-pointer custom-hvr-img-zoom" >
                                <img class="img-fluid" src="{{ asset('storage/'.$product->image) }}" alt="">
                            </div>
                            <div class="p-3">
                                <h5 class="my-2">{{ $product->name }}</h5>
                                <p class="custom-tablet-screen-p-font">{{ $product->short_description }}</p>
                                <br>
                                <small class="">Категодија: {{ $product->p_sub_category->sub_category }}</small>
                            </div>

                        </div>
                    </a>   
                </div>

                <div id="myDescriptionModal{{ $product->id }}" class="modal fade" role="dialog">
                    <div class="modal-dialog modal-md modal-dialog-centered modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Опис</h4>
                            </div>
                            <div class="modal-body">
                                {!! $product->description !!}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default btn-outline-primary" data-dismiss="modal">Затвори</button>
                            </div>
                        </div>
                    </div>
                </div>
                
            @empty
                <h3>No products added</h3>
            @endforelse

        </div>
    </div>
</div>

OnlineMedical/resources/views/user/inc/welcome_page/our_services.blade.php
<div id="our_services" class="py-5 row justify-content-center align-items-center">
    <div class="col-md-6 text-center py-5">
        <h1 class="custom-tablet-screen-heading-font"> <strong> Наши услуги </strong></h1>
        <div class="custom-hr"></div>
        <p class="custom-tablet-screen-p-font">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium libero repudiandae possimus sequi! Numquam, ex amet. Praesentium ullam iusto nam, fugiat esse</p>
    </div>
    <div class="col-md-10">
        <div class="row justify-content-center align-items-center">
            
            <div class="card-deck">
                
                    <div class="card border border-primary shadow">
                        <a href="{{route('user.show_all_questionnaires')}}" class="text-decoration-none">
                            <div class="card-body">
                                <div class="services-icon text-primary display-4 p-2">
                                    <i class="fas fa-clipboard-list"></i>
                                </div>
                                <h4 class="border-bottom border-primary">Персонален медицински асистент</h4>
                                <p class="custom-tablet-screen-p-font">Пополнувате краток прашалник и веднаш добивате одговор со препорака за лек или достапна клиника за вашиот проблем</p>    
                            </div>
                        </a>
                    </div>    
                
                
                
                    <div class="card border border-primary shadow">
                        <a href="{{route('user.show_all_products')}}" class="text-decoration-none">
                            <div class="card-body">
                                <div class="services-icon text-primary display-4 p-2">
                                    <i class="fas fa-capsules"></i>
                                </div>
                                <h4 class="border-bottom border-primary">Палета на производи</h4>
                                <p class="custom-tablet-screen-p-font">Палетата на производи служи како упатство на употреба за истите и каде може да ги набавите</p>    
                            </div>
                        </a>    
                    </div>    
                

                
                    <div class="card border border-primary shadow">
                        <a href="{{route('user.show_all_clinics')}}" class="text-decoration-none">
                            <div class="card-body">
                                <div class="services-icon text-primary display-4 p-2">
                                    <i class="fas fa-clinic-medical"></i>
                                </div>
                                <h4 class="border-bottom border-primary">24/7 Клиники</h4>
                                <p class="custom-tablet-screen-p-font">Базата на клиники служи да се информирате кои клиники имаат дежурна служба 24/7, да дојдете до нивен телефонски број и локација</p>    
                            </div>
                        </a>    
                    </div>    
                
            </div>

            <div class="card-deck mt-3">
                <div class="card border border-primary shadow">
                    <a href="{{route('user.show_all_blogs')}}" class="text-decoration-none">
                        <div class="card-body">
                            <div class="services-icon text-primary display-4 p-2">
                                <i class="fas fa-book-reader"></i>
                            </div>
                            <h4 class="border-bottom border-primary">Блогови</h4>
                            <p class="custom-tablet-screen-p-font">Блоговите се напишани од медицински лица со цел да го подобрат секојдневниот живот, а воедно и да побијат некој од најчестите митови</p>    
                        </div>    
                    </a>
                </div>    

                
                    <div class="card border border-primary shadow">
                        <a href="{{route('user.show_fitness_page')}}" class="text-decoration-none">
                            <div class="card-body">
                                <div class="services-icon text-primary display-4 p-2">
                                    <i class="fas fa-dumbbell"></i>
                                </div>
                                <h4 class="border-bottom border-primary">Физичко здравје и фитнес</h4>
                                <p class="custom-tablet-screen-p-font">Блоговите се напишани од медицински лица со цел да го подобрат секојдневниот живот, а воедно и да побијат некој од најчестите митови</p>    
                            </div>
                        </a>
                    </div>    
                

                
                    <div class="card border border-primary shadow">
                        <a href="{{route('user.show_psychology_page')}}" class="text-decoration-none">
                            <div class="card-body">
                                <div class="services-icon text-primary display-4 p-2">
                                    <i class="fas fa-brain"></i>
                                </div>
                                <h4 class="border-bottom border-primary">Ментално здравје</h4>
                                <p class="custom-tablet-screen-p-font">Блоговите се напишани од медицински лица со цел да го подобрат секојдневниот живот, а воедно и да побијат некој од најчестите митови</p>    
                            </div>    
                        </a>
                    </div>    
                
            </div>
        </div>        
    </div>
</div>

OnlineMedical/resources/views/user/inc/welcome_page/our_team.blade.php
<div id="our_team" class="row bg-light">
    <div class="col-md-12 text-center">
        <h1 class="my-2 custom-tablet-screen-heading-font"><strong> Вашите онлајн херои </strong></h1>
        <div class="custom-hr"></div>
    </div>
    <div class="col-md-10 offset-md-1">
        <div class="row">
            @for ($i = 0; $i < 4; $i++)                
                <div class="col-md-3 text-center">
                    <div class="my-2">
                        <img class="img-fluid rounded" src="https://source.unsplash.com/800x600/?doctors" alt="">
                    </div>
                    <h3 class="my-2">Name</h3>
                    <p class="my-2">Title</p>
                    <hr>
                    <div>
                        <i class="mx-2 fab fa-linkedin-in"></i>
                        <i class="mx-2 fab fa-facebook-f"></i>
                        <i class="mx-2 fab fa-google-plus-g"></i>
                        <i class="mx-2 fab fa-twitter"></i>
                    </div>
                </div>
            @endfor
        </div>
    </div>
</div>

OnlineMedical/resources/views/user/inc/welcome_page/sponsors.blade.php
<div id="sponsors" class="row h-25 bg-light align-items-center text-center">
    <div class="col-md-3">
        <h3>Alcon</h3>
    </div>
    <div class="col-md-3">
        <h3>Unimed</h3>
    </div>
    <div class="col-md-3">
        <h3>Nutrishop</h3>
    </div>
    <div class="col-md-3">
        <h3>Denica</h3>
    </div>
</div>

OnlineMedical/resources/views/user/inc/welcome_page/statistics.blade.php
<div id="statistics" class="row bg-black justify-content-around align-items-center shadow-lg">
    <div class="col-md-4">
        <h1 class="">Запознајте не преку бројки</h1>
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-6">
                <h3 class="text-center"><span class="h2">2323<span class="text-primary">+</span></><br> Задоволни корисници </h3>
            </div>
            <div class="col-md-6">
                <h3 class="text-center"><span class="h2">2323<span class="text-primary">+</span></><br> Дневни посети </h3>
            </div>
        </div>
    </div>
</div>

OnlineMedical/resources/views/user/inc/welcome_page/what_our_clients_say.blade.php
<div id="what_our_clients_say" class="row shadow">
    <div class="col-md-12">
        <h1 class="text-center mt-4 custom-tablet-screen-heading-font"> <strong> Што велат нашите корисници? </strong></h1>
        <div class="custom-hr"></div>
    </div>

    <div class="w-100">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="d-block w-100" height="300px" src="https://www.publicdomainpictures.net/pictures/30000/velka/plain-white-background.jpg" alt="First slide">
                <div class="carousel-caption text-dark d-md-block">
                    <p class="custom-tablet-screen-p-font">Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum odit vitae sequi porro, rerum quibusdam consectetur officiis doloribus perspiciatis veritatis, laudantium nostrum fugit illum, magni neque cupiditate accusantium! Rem, accusamus.</p>
                    <h1>Stefan</h1>
                </div>
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" height="300px" src="https://www.publicdomainpictures.net/pictures/30000/velka/plain-white-background.jpg" alt="Second slide">
                <div class="carousel-caption text-dark d-md-block">
                    <p class="custom-tablet-screen-p-font">Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum odit vitae sequi porro, rerum quibusdam consectetur officiis doloribus perspiciatis veritatis, laudantium nostrum fugit illum, magni neque cupiditate accusantium! Rem, accusamus.</p>
                    <h1>Kiril</h1>
                </div>
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" height="300px" src="https://www.publicdomainpictures.net/pictures/30000/velka/plain-white-background.jpg" alt="Third slide">
                <div class="carousel-caption text-dark d-md-block">
                    <p class="custom-tablet-screen-p-font">Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum odit vitae sequi porro, rerum quibusdam consectetur officiis doloribus perspiciatis veritatis, laudantium nostrum fugit illum, magni neque cupiditate accusantium! Rem, accusamus.</p>
                    <h1>Boban</h1>
                </div>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
    </div>
</div>